/*
 * @Date: 2024-04-24 17:30:55
 * @LastEditors: Chenqy
 * @LastEditTime: 2024-04-24 17:36:39
 * @FilePath: \CAUC_Bookinge:\cauc_museum\cauc_admin\components.d.ts
 * @Description: True or False
 */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Brand: typeof import('./src/components/brand/brand.vue')['default']
    ButtonBox: typeof import('./src/components/box/buttonBox.vue')['default']
    Calendar: typeof import('./src/components/calender/calendar.vue')['default']
    CommonButton: typeof import('./src/components/button/commonButton.vue')['default']
    CommonCheckbox: typeof import('./src/components/checkbox/commonCheckbox.vue')['default']
    CRadio: typeof import('./src/components/radio/c-radio.vue')['default']
    CustomDatePicker: typeof import('./src/components/picker/customDatePicker.vue')['default']
    CustomLink: typeof import('./src/components/box/customLink.vue')['default']
    CustomMessageBox: typeof import('./src/components/msgBox/customMessageBox.vue')['default']
    CustomSelect: typeof import('./src/components/select/customSelect.vue')['default']
    Dialog: typeof import('./src/components/dialog/dialog.vue')['default']
    DrawerButton: typeof import('./src/components/button/drawerButton.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Header: typeof import('./src/components/header/header.vue')['default']
    HistoryBox: typeof import('./src/components/box/historyBox.vue')['default']
    IconButton: typeof import('./src/components/button/iconButton.vue')['default']
    IconInput: typeof import('./src/components/input/iconInput.vue')['default']
    LeftMenu: typeof import('./src/components/menu/leftMenu.vue')['default']
    MenuItem: typeof import('./src/components/menu/menuItem.vue')['default']
    MonthPicker: typeof import('./src/components/picker/monthPicker.vue')['default']
    MsgPanel: typeof import('./src/components/panel/msg-panel/msg-panel.vue')['default']
    MulCheckBox: typeof import('./src/components/checkbox/mulCheckBox.vue')['default']
    MulInput: typeof import('./src/components/input/mulInput.vue')['default']
    MulSwitch: typeof import('./src/components/switch/mulSwitch.vue')['default']
    PopoverButton: typeof import('./src/components/button/popoverButton.vue')['default']
    RadioCheckBox: typeof import('./src/components/checkbox/radioCheckBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleDialog: typeof import('./src/components/dialog/simpleDialog.vue')['default']
    Star: typeof import('./src/components/other/star.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
